// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgTw1kg3ogEQDCQ0aPoLC1pkTcj65T8Yo',
    appId: '1:134041370565:web:85b4a149cc32584377d5ac',
    messagingSenderId: '134041370565',
    projectId: 'pil-project-43392',
    authDomain: 'pil-project-43392.firebaseapp.com',
    storageBucket: 'pil-project-43392.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOx6T1dVI7Q3k3_gxfbNgvStQdA9S_Kz8',
    appId: '1:134041370565:android:ad7bd3bb0e33218c77d5ac',
    messagingSenderId: '134041370565',
    projectId: 'pil-project-43392',
    storageBucket: 'pil-project-43392.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6mbn75lONmUU1o5YX0bJX4b3cJxj3rLk',
    appId: '1:134041370565:ios:fbc0eddfa73b264377d5ac',
    messagingSenderId: '134041370565',
    projectId: 'pil-project-43392',
    storageBucket: 'pil-project-43392.firebasestorage.app',
    androidClientId:
        '134041370565-oimoem6uaehep92qn36v3naj0v9fdopi.apps.googleusercontent.com',
    iosClientId:
        '134041370565-jsd5lbjp6tsmuuq35l37jib5jrc8fako.apps.googleusercontent.com',
    iosBundleId: 'com.example.pilProject',
  );
}
